### PR TITLE
add missing ressource files

### PR DESCRIPTION
**Pull request by gabx**
```
% perl Makefile.PL INSTALLDIR='perl'
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	resources/bootstrap.min.css
	resources/bootstrap.min.js
	resources/font-awesome.min.css
	resources/fontawesome-webfont.ttf
Please inform the author.
```

### CODE REVIEW

**Comment by gabx** [comment]
the use of /usr/local/bin is depreciated and not recommended upstream. Then, we need to use a fixed path for the scripts to be coherent with the systemd service file.

**Comment by gabx** [comment]
1- best practice is to give the service file the name of the command
2- we can do same for pgcluu (service + timer)
3- run pgcluu_collect for 240 sec every 2 hours
4- just start the timer, no need to start the service file. The timer will take care of it

**Comment by darold** [comment]
Thanks for your pull request Arno. I have just updated the resources files, especially to replace external font file fontawesome-webfont.ttf by the base64 embedded version. I've also updated the __DATA__ part of pgcluu with updated resources files. Files are provided into the resources/ directory to be used with the CGI version of pgcluu. The standalone version of pgcluu embedded all files in the DATA section and copy them as separate files when a report is generated. This greatly simplify things when you are working on auditing a PostgreSQL server, you just need pgcluu_collectd and pgcluu. The inconvenient is that it is more time consuming to maintain. I have moved the resources/ directory into the cgi-bin/ directory to be less confusing.

Also note that files in cgi-bin/ directory is a work in progress to add "real time" interface to a pgcluu_collectd daemon. It still need lot of works.

Regards,

**Comment by gabx** [comment]
In fact, I am testing on my server this: only one service + one timer. The service will have as ExecStartPre = /usr/bin/pgcluu_collectd -i 240 $OUTPUTDIR
ExecStart = /usr/bin/pgcluu [options] [-i sar_file [--from-sa-file] | -I sadc_file]
    [input_dir]
ExecStartPost= <here we can maybe do some cleaning>

In that way, one timer will trigger the whole process. Will be back when everything is sorted and working cleanely. 

Regards.

**Pull request merged**
